# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_excel('Research data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, [-1]].values

In [3]:
print(X)

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
print(y)

[[ 66.193]
 [ 66.193]
 [ 66.193]
 ...
 [158.94 ]
 [159.03 ]
 [159.13 ]]


**Splitting data into Test and Training set**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## **Feature Scaling**

In [6]:
from sklearn.preprocessing import StandardScaler
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.transform(y_test)

## **Training the SVR model kernel rbf on the whole dataset**

In [7]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

# **Training SVR model kernel linear**

In [8]:
from sklearn.svm import SVR
regressor2 = SVR(kernel = 'linear')
regressor2.fit(X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR(kernel='linear')

# **Training Multiple linear regression**

In [9]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(X_train, y_train)

LinearRegression()

## Predicting a new result SVR kernel rbf

In [10]:
y_pred = sc_y.inverse_transform(regressor.predict(X_test))
np.set_printoptions(precision = 2)

# Actual v/s prediction

In [11]:
print((np.concatenate((sc_y.inverse_transform(y_test.reshape(len(y_test),1)),y_pred.reshape(len(y_pred),1)),1)))

[[134.31 184.94]
 [126.88 184.94]
 [ 52.5   61.66]
 ...
 [124.33 155.14]
 [161.06 193.16]
 [105.99 115.39]]


# Predicting a new result SVR kernel linear

In [12]:
y_pred2 = sc_y.inverse_transform(regressor2.predict(X_test))
np.set_printoptions(precision = 2)

# Actual v/s Prediction

In [13]:
print((np.concatenate((sc_y.inverse_transform(y_test.reshape(len(y_test),1)),y_pred2.reshape(len(y_pred),1)),1)))

[[134.31 181.92]
 [126.88 181.92]
 [ 52.5   73.08]
 ...
 [124.33 160.44]
 [161.06 191.91]
 [105.99  74.75]]


# Predicting a new result Linear

In [14]:
y_linear = sc_y.inverse_transform(linear.predict(X_test))
np.set_printoptions(precision = 2)


# Actual v/s Prediction

In [15]:
print((np.concatenate((sc_y.inverse_transform(y_test.reshape(len(y_test),1)),y_linear.reshape(len(y_linear),1)),1)))

[[134.31 183.62]
 [126.88 183.62]
 [ 52.5   84.77]
 ...
 [124.33 160.81]
 [161.06 189.55]
 [105.99  78.98]]


## MAE of SVR results (kernel= rbf)

In [16]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(sc_y.inverse_transform(y_test) , y_pred)
print('SVR rbf kernel MAE = ', MAE)

SVR rbf kernel MAE =  65.4824531762593


In [23]:
from sklearn.metrics import r2_score
r2_score(sc_y.inverse_transform(y_test), y_pred)

0.13951005901549463

## MAE of SVR results (kernel = linear)

In [18]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(sc_y.inverse_transform(y_test) , y_pred2)
print('SVR linear kernel MAE = ', MAE)

SVR linear kernel MAE =  66.53251962669704


In [22]:
from sklearn.metrics import r2_score
r2_score(sc_y.inverse_transform(y_test), y_pred)

0.13951005901549463

## MAE of multiple linear regression results

In [20]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(sc_y.inverse_transform(y_test) , y_linear)
print('multiple linear regression MAE = ', MAE)

multiple linear regression MAE =  67.13535425854369


In [24]:
from sklearn.metrics import r2_score
r2_score(sc_y.inverse_transform(y_test), y_pred)

0.13951005901549463