# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_excel('Research data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
print(y)

[ 66.193  66.193  66.193 ... 158.94  159.03  159.13 ]


**Splitting data into Test and Training set**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## **Training the SVR model kernel rbf on the whole dataset**

In [6]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR()

# **Training SVR model kernel linear**

In [7]:
from sklearn.svm import SVR
regressor2 = SVR(kernel = 'linear')
regressor2.fit(X_train, y_train)

SVR(kernel='linear')

# **Training Multiple linear regression**

In [8]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(X_train, y_train)

LinearRegression()

## Predicting a new result SVR kernel rbf

In [9]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)

# Actual v/s prediction

In [10]:
print((np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1)))

[[134.31 185.01]
 [126.88 185.01]
 [ 52.5   60.93]
 ...
 [124.33 154.71]
 [161.06 192.69]
 [105.99 116.79]]


# Predicting a new result SVR kernel linear

In [11]:
y_pred2 = regressor2.predict(X_test)
np.set_printoptions(precision = 2)

# Actual v/s Prediction

In [12]:
print((np.concatenate((y_test.reshape(len(y_test),1),y_pred2.reshape(len(y_pred),1)),1)))

[[134.31 182.47]
 [126.88 182.47]
 [ 52.5   73.31]
 ...
 [124.33 160.62]
 [161.06 191.83]
 [105.99  73.21]]


# Predicting a new result Linear

In [13]:
y_linear = linear.predict(X_test)
np.set_printoptions(precision = 2)


# Actual v/s Prediction

In [14]:
print((np.concatenate((y_test.reshape(len(y_test),1),y_linear.reshape(len(y_linear),1)),1)))

[[134.31 183.62]
 [126.88 183.62]
 [ 52.5   84.77]
 ...
 [124.33 160.81]
 [161.06 189.55]
 [105.99  78.98]]


## MAE of SVR results (kernel= rbf)

In [15]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test , y_pred)
print('SVR rbf kernel MAE = ', MAE)

SVR rbf kernel MAE =  65.60367487368278


In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.13852548900257144

## MAE of SVR results (kernel = linear)

In [17]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test , y_pred2)
print('SVR linear kernel MAE = ', MAE)

SVR linear kernel MAE =  66.53673520473352


In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred2)

0.1326656005279938

## MAE of multiple linear regression results

In [19]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test , y_linear)
print('multiple linear regression MAE = ', MAE)

multiple linear regression MAE =  67.13535425854369


In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_linear)

0.1399883632480895