# Support Vector machine Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_excel('Research data.xlsx')
y = dataset.iloc[:, :-1].values
X = dataset.iloc[:, [-1]].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
print(X_train)

[[188.13 ]
 [247.93 ]
 [154.39 ]
 ...
 [ 16.556]
 [137.73 ]
 [249.2  ]]


In [5]:
print(y_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
print(X_test)

[[134.31 ]
 [126.88 ]
 [ 52.497]
 ...
 [ 99.893]
 [240.75 ]
 [121.61 ]]


In [7]:
print(y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[ 0.11024675]
 [ 0.76572709]
 [-0.25958447]
 ...
 [-1.77041186]
 [-0.44219823]
 [ 0.77964783]]


In [10]:
print(X_test)

[[-0.47968556]
 [-0.56112735]
 [-1.37645502]
 ...
 [-0.85693752]
 [ 0.6870256 ]
 [-0.61889293]]


## Training the Support Vector Classification model on the Training set

In [11]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.svm import SVC
sv = SVC(kernel = 'rbf', random_state = 0)


classifier = MultiOutputClassifier(sv, n_jobs=-1)
classifier.fit(X_train,y_train)



MultiOutputClassifier(estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                    class_weight=None, coef0=0.0,
                                    decision_function_shape='ovr', degree=3,
                                    gamma='scale', kernel='rbf', max_iter=-1,
                                    probability=False, random_state=0,
                                    shrinking=True, tol=0.001, verbose=False),
                      n_jobs=-1)

## Predicting the Test set results

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
X_test = sc.inverse_transform(X_test)

In [18]:
print(X_test[5000:5010])

[[155.06 ]
 [183.67 ]
 [135.1  ]
 [167.93 ]
 [130.78 ]
 [223.81 ]
 [156.01 ]
 [ 22.382]
 [189.78 ]
 [ 75.873]]


In [19]:
print(y_test[5000:5010])

[[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [20]:
print(y_pred[5000:5010])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


## Evaluation

In [ ]:
classifier.score(X_test,y_test)

In [26]:
from sklearn.metrics import accuracy_score, f1_score

In [28]:
accuracy_score(y_test.flatten(), y_pred.flatten())

0.9873823581699838

In [29]:
f1_score(y_test.flatten(), y_pred.flatten(), average = 'weighted')

0.9811135911692858

## Geometric mean

In [ ]:
!pip install -U imbalanced-learn

In [32]:
from imblearn.metrics import geometric_mean_score

In [33]:
geometric_mean_score(y_test.flatten(), y_pred.flatten(), average='weighted')

0.11161736847223036

## Hamming Loss

In [34]:
np.sum(np.not_equal(y_test, y_pred))/float(y_test.size)

0.01261764183001622