# Polynomial Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_excel('Research data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Training the Polynomial Regression model on the Training set

In [4]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [30]:
y_pred = regressor.predict(poly_reg.transform(X_test))

list = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
import sys
import numpy
numpy.set_printoptions(threshold= 2000)

print(list[:100])

[[184.48 134.31]
 [184.48 126.88]
 [ 66.35  52.5 ]
 [184.48 135.84]
 [184.48  75.83]
 [184.48 200.58]
 [184.48  94.08]
 [184.48 219.9 ]
 [184.48 225.  ]
 [125.47 158.39]
 [ 65.48  49.14]
 [184.48 220.37]
 [184.48 229.73]
 [120.49 124.59]
 [184.48 153.76]
 [184.48 228.3 ]
 [184.48 221.27]
 [184.48 156.89]
 [184.48 198.76]
 [184.48 234.37]
 [184.48 225.71]
 [157.69 164.82]
 [184.48  46.09]
 [157.69 115.28]
 [184.48 208.58]
 [184.48  11.98]
 [184.48 247.36]
 [288.9  354.8 ]
 [118.53 115.84]
 [184.48 270.21]
 [184.48 144.92]
 [184.48 187.48]
 [ 65.48  10.8 ]
 [ 90.93 104.09]
 [184.48 251.06]
 [184.48 219.29]
 [108.73 127.45]
 [184.48 221.24]
 [184.48 129.22]
 [184.48 154.86]
 [184.48 158.9 ]
 [184.48 203.09]
 [125.47 169.91]
 [184.48  77.81]
 [120.49 145.57]
 [184.48 284.16]
 [184.48 333.87]
 [184.48 114.94]
 [145.77 181.31]
 [184.48 320.99]
 [288.9  309.41]
 [184.48 167.91]
 [184.48  14.11]
 [198.92 215.7 ]
 [195.83 173.9 ]
 [184.48 227.09]
 [184.48 261.23]
 [184.48 254.52]
 [184.48 139.4

## Evaluating the Model Performance

In [18]:
from sklearn.metrics import r2_score
print(y_test)
print(y_pred)
r2_score(y_test, y_pred)

[134.31 126.88  52.5  ... 124.33 161.06 105.99]
[184.48 184.48  66.35 ... 157.69 190.91 109.94]


-16194123759449.082

In [19]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test, y_pred)
print("Polynomial regression MAE = ", MAE)

Polynomial regression MAE =  1565534.4480995012
